name: Get Feed

on:
  schedule:
    - cron: '*/5 * * * *' # default was 30 12 * * * # 6pm IST 
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY:  300 # in seconds, default ws 86400
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/abdullahtariq1171/notion-feeder/build/dist/index.js
          node index.js
